apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true
    uid: prometheus_datasource 
    jsonData:
      timeInterval: 5s

  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo:3200
    version: 1
    editable: true
    uid: tempo_datasource
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    version: 1
    editable: true
    uid: loki_datasource
    jsonData:
      derivedFields:
        - datasourceUid: tempo_datasource
          matcherRegex: '"trace_id":\s*"(\w+)"'
          name: TraceID
          url: '$${__value.raw}' # Fallback URL (required syntax)